version: '3.8'

services:
  ai-proxy:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_API_KEY_REVO_1_0=${GOOGLE_API_KEY_REVO_1_0}
      - GOOGLE_API_KEY_REVO_1_5=${GOOGLE_API_KEY_REVO_1_5}
      - GOOGLE_API_KEY_REVO_2_0=${GOOGLE_API_KEY_REVO_2_0}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
